<?php
require_once __DIR__ . '/public-common.php';

    $isGuest = !isset($_SESSION['user_id']) && ($_GET['guest'] ?? '') === '1';
    if (!$isGuest && !isset($_SESSION['user_id'])) {
        header('Location: index.php');
        exit();
    }
    if (!$isGuest && ($_SESSION['role'] ?? 'user') === 'admin') {
        header('Location: dashboard.php');
        exit();
    }
    
    $displayName = publicText($isGuest ? 'Guest visitor' : ($_SESSION['username'] ?? 'Resident'));
    $updates = publicRows('SELECT title, body, published_at FROM public_updates WHERE is_published = 1 ORDER BY published_at DESC LIMIT 6');
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My community dashboard | Barangay San Isidro</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <style>
        :root { --navy:#103b4a; --teal:#087f7b; --mint:#d8f2e7; --gold:#f3bf62; --paper:#f7fbf8; --ink:#17323a; --muted:#62777a; --line:#dbe9e2; }
        * { box-sizing:border-box; } body { margin:0; background:var(--paper); color:var(--ink); font-family:Arial,sans-serif; }
        header { background:var(--navy); color:white; padding:18px max(24px,calc((100% - 1124px)/2)); display:flex; align-items:center; justify-content:space-between; gap:20px; }
        .brand { color:white; text-decoration:none; font:500 21px Georgia,serif; } header nav { display:flex; align-items:center; gap:20px; } header a { color:#d8f2e7; text-decoration:none; font-size:13px; } .menu-button { display:none; color:white; background:none; border:0; font-size:20px; }
        .logout { border:1px solid rgba(255,255,255,.4); padding:9px 13px; border-radius:3px; }
        main { max-width:1124px; margin:auto; padding:54px 24px 80px; } .welcome { display:flex; align-items:end; justify-content:space-between; gap:20px; margin-bottom:34px; }
        h1,h2,h3 { font-family:Georgia,serif; font-weight:500; color:var(--navy); } h1 { font-size:42px; margin:8px 0; } h2 { font-size:28px; margin:0; } h3 { font-size:20px; margin:18px 0 8px; }
        .eyebrow { color:var(--teal); font-size:12px; letter-spacing:1.5px; text-transform:uppercase; font-weight:700; } .welcome p { color:var(--muted); margin:0; line-height:1.5; }
        .guest-note { border:1px solid #ecd39f; background:#fff8e8; padding:14px 17px; color:#76591d; font-size:13px; line-height:1.45; max-width:330px; }
        .section-head { display:flex; justify-content:space-between; align-items:end; gap:20px; margin:42px 0 18px; } .section-head p { color:var(--muted); font-size:14px; margin:0; }
        .grid { display:grid; grid-template-columns:repeat(4,1fr); gap:14px; } .card { background:white; border:1px solid var(--line); padding:24px 20px; min-height:220px; position:relative; }
        .card .icon { color:var(--teal); font-size:23px; } .card p { color:var(--muted); font-size:14px; line-height:1.5; min-height:64px; } .card a { color:var(--teal); font-size:13px; font-weight:700; text-decoration:none; }
        .card a i { margin-left:5px; } .tools { display:flex; gap:12px; margin-top:20px; } .tool { color:var(--muted); font-size:12px; text-decoration:none; border:0; background:none; cursor:pointer; padding:0; } .tool.locked { opacity:.65; } .tool.saved { color:var(--teal); }
        .quick-grid { display:grid; grid-template-columns:repeat(4,1fr); gap:14px; } .quick { background:var(--mint); border:1px solid #bfe1d2; padding:19px; color:var(--navy); text-decoration:none; min-height:115px; } .quick i { color:var(--teal); } .quick strong { display:block; margin-top:18px; font:500 17px Georgia,serif; }
        .bottom { display:grid; grid-template-columns:1fr 1fr; gap:14px; margin-top:42px; } .panel { background:white; border:1px solid var(--line); padding:24px; } .panel p { color:var(--muted); font-size:14px; line-height:1.5; }
        .update { border-top:1px solid var(--line); padding:13px 0; font-size:14px; } .update span { color:var(--teal); font-size:11px; font-weight:700; margin-right:12px; }
        .button { display:inline-flex; align-items:center; gap:8px; border:0; border-radius:3px; padding:11px 15px; background:var(--teal); color:white; text-decoration:none; font-size:13px; font-weight:700; cursor:pointer; }
        .modal { position:fixed; inset:0; display:grid; place-items:center; padding:20px; background:rgba(16,59,74,.55); z-index:20; } .modal[hidden] { display:none; } .modal-card { width:min(430px,100%); background:white; padding:28px; box-shadow:0 20px 60px rgba(0,0,0,.2); position:relative; } .modal-close { position:absolute; top:14px; right:14px; border:0; background:none; color:var(--muted); font-size:20px; cursor:pointer; } .modal h2 { padding-right:25px; } .modal p { color:var(--muted); font-size:14px; line-height:1.5; } .modal label { display:block; color:var(--navy); font-size:12px; font-weight:700; margin:16px 0 6px; } .modal input { width:100%; padding:12px; border:1px solid #cbded5; border-radius:3px; } .modal-message { display:none; padding:10px; margin-top:12px; background:#fde8e5; color:#9a332b; font-size:13px; }
        @media (max-width:850px) { .grid,.quick-grid { grid-template-columns:repeat(2,1fr); } .welcome { align-items:start; flex-direction:column; } } @media (max-width:600px) { header nav { display:none; } .menu-button { display:block; } header.open nav { display:flex; position:absolute; top:62px; right:18px; background:var(--navy); padding:16px; flex-direction:column; align-items:stretch; z-index:5; } main { padding:38px 18px; } h1 { font-size:34px; } .grid,.quick-grid,.bottom { grid-template-columns:1fr; } }
    </style>
</head>
<body>
    <header id="site-header"><a class="brand" href="index.php">Barangay San Isidro</a><button class="menu-button" type="button" aria-label="Open navigation" aria-expanded="false" onclick="toggleMenu(this)"><i class="fa-solid fa-bars"></i></button><nav><a href="info.php">Public information</a><?php if ($isGuest): ?><a class="logout" href="auth.php">Login / register</a><?php else: ?><a class="logout" href="bootstrap/logout.php">Log out</a><?php endif; ?></nav></header>
    <main>
        <section class="welcome"><div><div class="eyebrow">Community portal</div><h1>Good day, <?= $displayName ?>.</h1><p>One place for local information, services, and community participation.</p></div><?php if ($isGuest): ?><div class="guest-note"><strong>Guest mode</strong><br>You're browsing public content. Sign in to save items, subscribe to alerts, and submit requests.</div><?php else: ?><div class="guest-note" style="background:var(--mint);border-color:#bfe1d2;color:#165a4d"><strong>Welcome back</strong><br>Your saved pages and requests will stay connected to your account.</div><?php endif; ?></section>
        <section><div class="section-head"><h2>Explore information</h2><p>Choose a topic to get started.</p></div><div class="grid">
            <article class="card"><span class="icon"><i class="fa-solid fa-landmark"></i></span><h3>Community profile</h3><p>Meet the barangay, learn its history, and view current officials.</p><a href="community-profile">View details <i class="fa-solid fa-arrow-right"></i></a><div class="tools"><button class="tool <?= $isGuest ? 'locked' : '' ?>" type="button" data-gated="save" data-item="community-profile"><i class="fa-regular fa-bookmark"></i> Save</button><button class="tool" type="button" data-share="community-profile"><i class="fa-solid fa-print"></i> Print</button></div></article>
            <article class="card"><span class="icon"><i class="fa-solid fa-chart-simple"></i></span><h3>Census & statistics</h3><p>Browse population, household, and demographic information.</p><a href="census-statistics">Search statistics <i class="fa-solid fa-arrow-right"></i></a><div class="tools"><button class="tool <?= $isGuest ? 'locked' : '' ?>" type="button" data-gated="save" data-item="census-statistics"><i class="fa-regular fa-bookmark"></i> Save</button><button class="tool <?= $isGuest ? 'locked' : '' ?>" type="button" data-gated="share" data-share="census-statistics"><i class="fa-solid fa-share-nodes"></i> Share</button></div></article>
            <article class="card"><span class="icon"><i class="fa-solid fa-hand-holding-heart"></i></span><h3>Services & programs</h3><p>Find schedules, contact information, and the latest updates.</p><a href="services-programs">View updates <i class="fa-solid fa-arrow-right"></i></a><div class="tools"><button class="tool <?= $isGuest ? 'locked' : '' ?>" type="button" data-gated="subscribe"><i class="fa-regular fa-bell"></i> Subscribe</button></div></article>
            <article class="card"><span class="icon"><i class="fa-solid fa-file-lines"></i></span><h3>Official documents</h3><p>Access public records, ordinances, and certificate requirements.</p><a href="<?= $isGuest ? 'auth.php' : 'official-documents' ?>">Request a service <i class="fa-solid fa-arrow-right"></i></a><div class="tools"><a class="tool" href="official-documents"><i class="fa-solid fa-download"></i> Download</a><a class="tool" href="official-documents#print"><i class="fa-solid fa-print"></i> Print</a></div></article>
        </div></section>
        <section><div class="section-head"><h2>Community actions</h2><p>Help the office respond to what matters.</p></div><div class="quick-grid"><a class="quick" href="info.php#feedback"><i class="fa-solid fa-comment-dots"></i><strong>Give feedback</strong></a><a class="quick" href="info.php#report"><i class="fa-solid fa-triangle-exclamation"></i><strong>Report an issue</strong></a><a class="quick" href="services-programs#rsvp"><i class="fa-solid fa-calendar-check"></i><strong>Attend an event</strong></a><a class="quick" href="<?= $isGuest ? '#' : 'certificate.php' ?>" <?= $isGuest ? 'data-gated="certificate"' : '' ?>><i class="fa-solid fa-file-circle-check"></i><strong>Get a certificate</strong></a></div></section>
        <section class="bottom"><div class="panel"><h2>Recent updates</h2><?php if ($updates): foreach ($updates as $update): ?><div class="update"><span><?= publicText(strtoupper(date('M d', strtotime($update['published_at'] ?? 'now')))) ?></span><?= publicText($update['title']) ?></div><?php endforeach; else: ?><div class="update"><span>INFO</span>Community updates will appear here when published.</div><?php endif; ?><a href="services-programs" style="display:inline-block;margin-top:14px;color:var(--teal);font-size:13px;font-weight:700">See all updates <i class="fa-solid fa-arrow-right"></i></a></div><div class="panel" id="saved"><h2><?= $isGuest ? 'Make it yours' : 'Your saved space' ?></h2><p><?= $isGuest ? 'Create an account to keep important pages close, receive alerts, and track every request with a reference number.' : 'Your saved information and notification preferences will appear here as you use the portal.' ?></p><?php if ($isGuest): ?><a class="button" href="auth.php">Create account</a><?php else: ?><span style="color:var(--teal);font-size:13px"><i class="fa-regular fa-bookmark"></i> Saved items are ready to collect</span><?php endif; ?></div></section>
    </main>
    <div class="modal" id="login-modal" hidden><div class="modal-card"><button class="modal-close" type="button" aria-label="Close" onclick="closeLogin()">&times;</button><h2>Login to continue</h2><p>Sign in or create an account to use this dashboard action.</p><div class="modal-message" id="modal-message"></div><form id="modal-login"><label for="modal-username">Username</label><input id="modal-username" name="username" required autocomplete="username"><label for="modal-password">Password</label><input id="modal-password" name="password" type="password" required autocomplete="current-password"><button class="button" style="margin-top:18px;width:100%;justify-content:center" type="submit">Login</button></form><a href="auth.php" style="display:block;text-align:center;color:var(--teal);font-size:13px;margin-top:16px">Create an account</a></div></div>
    <script>
        const isGuest = <?= $isGuest ? 'true' : 'false' ?>;
        let pendingAction = null;
        function toggleMenu(button) { const header = document.getElementById('site-header'); const open = header.classList.toggle('open'); button.setAttribute('aria-expanded', open); }
        function openLogin(action) { pendingAction = action; document.getElementById('login-modal').hidden = false; document.getElementById('modal-username').focus(); }
        function closeLogin() { document.getElementById('login-modal').hidden = true; }
        function saveItem(button) { const key = 'brgy-saved-' + button.dataset.item; const saved = localStorage.getItem(key) === '1'; localStorage.setItem(key, saved ? '0' : '1'); button.classList.toggle('saved', !saved); button.innerHTML = saved ? '<i class="fa-regular fa-bookmark"></i> Save' : '<i class="fa-solid fa-bookmark"></i> Saved'; }
        document.querySelectorAll('[data-gated]').forEach(element => element.addEventListener('click', event => { if (isGuest) { event.preventDefault(); openLogin(element.dataset.gated); return; } if (element.dataset.gated === 'save') saveItem(element); if (element.dataset.gated === 'subscribe') window.location.href = 'services-programs#alerts'; if (element.dataset.gated === 'share') shareItem(element.dataset.share); }));
        function shareItem(item) { if (navigator.share) navigator.share({ title:item, url:location.origin + '/' + item }); else if (navigator.clipboard) navigator.clipboard.writeText(location.href).then(() => alert('Page link copied.')); else alert('Copy this page link to share it.'); }
        document.querySelectorAll('[data-share]').forEach(element => element.addEventListener('click', () => { if (element.dataset.share === 'official-documents') { window.location.href = 'official-documents'; return; } if (navigator.share) navigator.share({ title: element.dataset.share, url: location.origin + '/' + element.dataset.share }); else if (navigator.clipboard) navigator.clipboard.writeText(location.href).then(() => alert('Page link copied.')); else alert('Copy this page link to share it.'); }));
        document.getElementById('modal-login').addEventListener('submit', async event => { event.preventDefault(); const message = document.getElementById('modal-message'); try { const response = await fetch('bootstrap/login.php', { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify(Object.fromEntries(new FormData(event.currentTarget))) }); const data = await response.json(); if (data.status === 'success') { window.location.href = 'user-dashboard.php' + (pendingAction ? '?action=' + encodeURIComponent(pendingAction) : ''); return; } message.textContent = data.message || 'Invalid username or password.'; } catch (error) { message.textContent = 'The service is temporarily unavailable.'; } message.style.display = 'block'; });
    </script>
</body>
</html>